export const categories = [
  { id: 'cameras', label: 'Caméras' },
  { id: 'lenses', label: 'Optiques' },
  { id: 'lights', label: 'Lumière' },
  { id: 'audio', label: 'Audio' },
  { id: 'kits', label: 'Packs tournage' },
]

export const products = [
  {
    id: 'sony-fx3',
    category: 'cameras',
    name: 'Sony FX3',
    brand: 'Sony',
    sensor: 'Full-frame',
    mount: 'E-mount',
    priceDay: 120,
    priceWeek: 650,
    image: '/og-image.png',
    notes: ['S-Log3', '4K 120p', 'Compact'],
  },
  {
    id: 'bmpcc-6k',
    category: 'cameras',
    name: 'Blackmagic Pocket 6K',
    brand: 'Blackmagic',
    sensor: 'Super 35',
    mount: 'EF',
    priceDay: 90,
    priceWeek: 500,
    image: '/og-image.png',
    notes: ['BRAW', '6K', 'Color science'],
  },
  {
    id: 'a7s-iii',
    category: 'cameras',
    name: 'Sony A7S III',
    brand: 'Sony',
    sensor: 'Full-frame',
    mount: 'E-mount',
    priceDay: 100,
    priceWeek: 560,
    image: '/og-image.png',
    notes: ['Low-light', '4K 120p', '10-bit'],
  },
  {
    id: 'sigma-18-35',
    category: 'lenses',
    name: 'Sigma 18–35mm f/1.8',
    brand: 'Sigma',
    mount: 'EF',
    priceDay: 25,
    priceWeek: 130,
    image: '/og-image.png',
    notes: ['Zoom', 'f/1.8', 'EF'],
  },
  {
    id: 'aputure-600x',
    category: 'lights',
    name: 'Aputure 600x',
    brand: 'Aputure',
    priceDay: 45,
    priceWeek: 240,
    image: '/og-image.png',
    notes: ['Bi-color', '600W', 'Bowens'],
  },
  {
    id: 'rode-ntg5',
    category: 'audio',
    name: 'Rode NTG5',
    brand: 'Rode',
    priceDay: 20,
    priceWeek: 110,
    image: '/og-image.png',
    notes: ['Shotgun', 'Léger'],
  },
  {
    id: 'kit-doc',
    category: 'kits',
    name: 'Kit documentaire',
    brand: 'Mix',
    priceDay: 180,
    priceWeek: 980,
    image: '/og-image.png',
    notes: ['Cam + Optique + Son + Lumière'],
  },
]

export function getProductById(id) {
  return products.find((p) => p.id === id) ?? null
}
